### ISSUE TITLE
test_hybrid_qkvpacked_attn 反向报错

### ISSUE THREAD

**Issue by ifromeast** [feifeibear/long-context-attention#120]
@feifeibear  在测试案例中
```
https://github.com/feifeibear/long-context-attention/blob/main/test/test_hybrid_qkvpacked_attn.py#L123 
```
该处直接返回，即未进行反向对齐，如果打开后，反向过程会报如下错误
```
[rank7]: Traceback (most recent call last):
[rank7]:   File "/data/zzd/repos/long-context-attention/test/test_hybrid_qkvpacked_attn.py", line 181, in <module>
[rank7]:     test(ring_impl_type)
[rank7]:   File "/data/zzd/repos/long-context-attention/test/test_hybrid_qkvpacked_attn.py", line 161, in test
[rank7]:     local_out.backward(local_dout)
[rank7]:   File "/home/zzd/miniconda3/envs/zzd-env/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
[rank7]:     torch.autograd.backward(
[rank7]:   File "/home/zzd/miniconda3/envs/zzd-env/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank7]:     _engine_run_backward(
[rank7]:   File "/home/zzd/miniconda3/envs/zzd-env/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank7]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank7]:   File "/home/zzd/miniconda3/envs/zzd-env/lib/python3.10/site-packages/torch/autograd/function.py", line 307, in apply
[rank7]:     return user_fn(self, *args)
[rank7]:   File "/home/zzd/miniconda3/envs/zzd-env/lib/python3.10/site-packages/yunchang/comm/all_to_all.py", line 253, in backward
[rank7]:     SeqAllToAll5D.apply(
[rank7]:   File "/home/zzd/miniconda3/envs/zzd-env/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
[rank7]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank7]: TypeError: apply() takes no keyword arguments
```

**Comment by feifeibear** [comment]
https://github.com/feifeibear/long-context-attention/pull/121

感谢帮助验证。现在AttnType.TORCH的反向实现是错误的。我已经更新了，不允许反向使用AttnType.TORCH。如果您有使用TORCH原生API实现flash attn反向的版本，希望帮助我补充。
